sudo: required
dist: bionic # (18.04)

language: cpp
compiler:
  - clang

addons:
  apt:
    update: true

services:
  - mysql

git:
  depth: 10

stages:
  - run

jobs:
  include:
    - stage: run
      before_install:
          - git config user.email "azerothcorebot@gmail.com" && git config user.name "AzerothCoreBot"
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd bin/; fi
          # import pending sql
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then source acore-db-pendings; fi
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd ..; fi
          # push changes to git if any
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git fetch --unshallow; fi
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git checkout $TRAVIS_BRANCH; fi
          - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ -n "$GITHUB_API_KEY" ]]; then git add -A . && git diff --cached --quiet || git commit -am "Import pending SQL update file..." -m "Referenced commit(s):$COMMIT_HASH" && git push https://$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_BRANCH; fi
          # sync staging with master
          - source ./apps/ci/ci-before_install.sh
      install:
        - source ./apps/ci/ci-install.sh
        - source ./apps/ci/ci-import-db.sh
      script:
        - source ./apps/ci/ci-compile.sh
        - source ./apps/ci/ci-worldserver-dry-run.sh
